import { dataBaseRT } from "./db";
import "./router";
import "./pages/welcome";
import "./pages/signup";
import "./pages/share-code";
import "./pages/access-room";
import "./pages/access-error";
import "./pages/game-rules";
import "./pages/error-guess-status";
import "./pages/game";
import "./pages/wait-room";
import "./pages/score";
import "./components/text";
import "./components/button";
import "./components/countdown";
import "./components/form";
import "./components/hands";
